apiVersion: v1
kind: Service
metadata:
  name: valaxy-service
  labels:
    app: regapp 
spec:
  selector:
    app: regapp 
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Explicitly expose via a known port
